# SPDX-FileCopyrightText: Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{% set version = "21.10.01" %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version='.'.join(environ.get('CUDA', '11.4').split('.')[:2]) %}
{% set build_num = 0 %}

package:
  name: libcudf
  version: {{ version }}

source:
  url: https://github.com/rapidsai/cudf/archive/v{{ version }}.tar.gz
  sha256: c3a5d5cae921496ef5800ab8b3580e4dbaab88115c4527d1bcddc06e9c4c43a3
  patches:
    # Fix the cmake export to include a version file
    - 001-external-table.patch

build:
  number: {{ build_num }}
  string: cuda_{{ cuda_version }}_h{{ PKG_HASH }}_{{ build_num }}_morpheus
  script_env:
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - PROJECT_FLASH
    - CCACHE_DIR
    - CCACHE_NOHASHDIR
    - CCACHE_COMPILERCHECK
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
  run_exports:
    - {{ pin_subpackage("libcudf", max_pin="x.x") }} *_morpheus
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - cmake>=3.22
    - ccache
    - ninja
  host:
    - librmm {{ minor_version }}.*
    - cudatoolkit {{ cuda_version }}.*
    - arrow-cpp 5.0.0 *cuda
    - arrow-cpp-proc * cuda
    - dlpack>=0.5,<0.6.0a0
    - gtest
    - gmock
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    - arrow-cpp * *cuda
    - arrow-cpp-proc * cuda
    - {{ pin_compatible('dlpack', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/lib/libcudf.so

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: cuDF GPU DataFrame core library
